name: grpc_testing_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-150.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.1
  grpc: ^3.0.2
  protoc_plugin: ^20.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true